services:
  api:
    build:
      context: .
      dockerfile: Dockerfile   # API Dockerfile at solution root
    image: dungeonexplorer-api:prod
    container_name: dungeonexplorer-api
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_URLS=http://+:8080

  react-client:
      build:
        context: ./DungeonExplorer.Client/React
        dockerfile: Dockerfile
      image: dungeonexplorer-react:prod
      container_name: dungeonexplorer-react
      ports:
        - "3000:80"
      depends_on:
        - api
      environment:
        - VITE_API_URL=http://api:8080