services:
  api:
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - DOTNET_RUNNING_IN_CONTAINER=true
      - DOTNET_HOST_PATH=/src/DungeonExplorer.Api
    volumes:
      - ./DungeonExplorer.Api:/src/DungeonExplorer.Api
      - ./DungeonExplorer.Service:/src/DungeonExplorer.Service
      - ./DungeonExplorer.Storage:/src/DungeonExplorer.Storage
      - ./DungeonExplorer.Domain:/src/DungeonExplorer.Domain

  client:
    environment:
      - VITE_API_URL=http://localhost:8080
    volumes:
      - ./DungeonExplorer.Client:/app