// <auto-generated />
using DungeonExplorer.Api.Storage;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DungeonExplorer.Api.Storage.Migrations
{
    [DbContext(typeof(DungeonContext))]
    [Migration("20260228122804_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.13");

            modelBuilder.Entity("DungeonExplorer.Api.Domain.DungeonMap", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Dungeons");
                });

            modelBuilder.Entity("DungeonExplorer.Api.Domain.Wall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("DungeonId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("X")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Y")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("DungeonId");

                    b.ToTable("Wall");
                });

            modelBuilder.Entity("DungeonExplorer.Api.Domain.DungeonMap", b =>
                {
                    b.OwnsOne("DungeonExplorer.Api.Domain.Position", "Goal", b1 =>
                        {
                            b1.Property<int>("DungeonMapId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("X")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DungeonMapId");

                            b1.ToTable("Dungeons");

                            b1.WithOwner()
                                .HasForeignKey("DungeonMapId");
                        });

                    b.OwnsOne("DungeonExplorer.Api.Domain.Position", "StartPosition", b1 =>
                        {
                            b1.Property<int>("DungeonMapId")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("X")
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Y")
                                .HasColumnType("INTEGER");

                            b1.HasKey("DungeonMapId");

                            b1.ToTable("Dungeons");

                            b1.WithOwner()
                                .HasForeignKey("DungeonMapId");
                        });

                    b.Navigation("Goal")
                        .IsRequired();

                    b.Navigation("StartPosition")
                        .IsRequired();
                });

            modelBuilder.Entity("DungeonExplorer.Api.Domain.Wall", b =>
                {
                    b.HasOne("DungeonExplorer.Api.Domain.DungeonMap", null)
                        .WithMany("Walls")
                        .HasForeignKey("DungeonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DungeonExplorer.Api.Domain.DungeonMap", b =>
                {
                    b.Navigation("Walls");
                });
#pragma warning restore 612, 618
        }
    }
}
